[metadata]
name = "htop"
version = "3.2.2"
description = "A system monitor made for the terminal"
deps = []
provides = ["/usr/bin/htop"]

[downloads]
"htop-3.2.2.tar.xz" = "https://github.com/htop-dev/htop/releases/download/3.2.2/htop-3.2.2.tar.xz"