[metadata]
name = "grub-bios"
description = "This package builds the gnu grub program but targeting bios machines"
version = "2.06-bios"
provides = [
    "/usr/bin/grub-bios-setup",
    "/usr/bin/grub-editenv",
    "/usr/bin/grub-file",
    "/usr/bin/grub-fstest",
    "/usr/bin/grub-glue-efi",
    "/usr/bin/grub-install",
    "/usr/bin/grub-kbdcomp",
    "/usr/bin/grub-macbless",
    "/usr/bin/grub-menulst2cfg",
    "/usr/bin/grub-mkconfig",
    "/usr/bin/grub-mkimage",
    "/usr/bin/grub-mklayout",
    "/usr/bin/grub-mknetdir",
    "/usr/bin/grub-mkpasswd-pbkdf2",
    "/usr/bin/grub-mkrelpath",
    "/usr/bin/grub-mkrescue",
    "/usr/bin/grub-mkstandalone",
    "/usr/bin/grub-ofpathname",
    "/usr/bin/grub-probe",
    "/usr/bin/grub-reboot",
    "/usr/bin/grub-render-label",
    "/usr/bin/grub-script-check",
    "/usr/bin/grub-set-default",
    "/usr/bin/grub-sparc64-setup",
    "/usr/bin/grub-syslinux2cfg"
]
deps = []

[downloads]
"grub-2.06.tar.xz" = "https://ftp.gnu.org/gnu/grub/grub-2.06.tar.xz"
"grub-2.06-upstream_fixes-1.patch" = "https://www.linuxfromscratch.org/patches/lfs/11.3/grub-2.06-upstream_fixes-1.patch"