[metadata]
name = "go"
version = "1.20.5"
description = "Build simple, secure, scalable systems with Go"
deps = []
provides = ["/usr/bin/go", "/usr/bin/gofmt"]

[downloads]
"go1.20.5.linux-amd64.tar.gz" = "https://go.dev/dl/go1.20.5.linux-amd64.tar.gz"