[metadata]
name = "network-manager"
description = "NetworkManager is a set of co-operative tools that make networking simple and straightforward."
version = "1.42.6"
deps = [
  "libs/libndp",
  "libs/jansson",
  "net/curl",
  "net/dhcp",
  "net/wpa_supplicant",
  "dev/newt",
  "security/polkit",
  "system/gobject-introspection",
  "libs/nss"
]
provides = [
  "/usr/bin/NetworkManager",
  "/usr/bin/nmcli",
  "/usr/bin/nmtui",
  "/usr/bin/nm-online",
  "/usr/bin/nmtui-connect",
  "/usr/bin/nmtui-edit",
  "/usr/bin/nmtui-hostname",
  "/usr/lib/libnm.so"
]

[downloads]
"NetworkManager-1.42.6.tar.xz" = "https://download.gnome.org/sources/NetworkManager/1.42/NetworkManager-1.42.6.tar.xz"