[metadata]
name = "wayland-protocols"
version = "1.31"
description = "The Wayland-Protocols package contains additional Wayland protocols that add functionality outside of protocols already in the Wayland core."
deps = ["display-servers/wayland"]
provides = []

[downloads]
"wayland-protocols-1.31.tar.xz" = "https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/1.31/downloads/wayland-protocols-1.31.tar.xz"