[metadata]
name = "ca-certificates"
description = "PKI verifies unknown identities over untrusted networks using a chain of trust and Mozilla provides trusted certificates for LFS-8.1."
version = "1.0.0"
provides = ["/usr/sbin/make-ca.sh"]
deps = []

[downloads]
"make-ca.sh-20170514" = "http://anduin.linuxfromscratch.org/BLFS/other/make-ca.sh-20170514"
"certdata.txt" = "http://anduin.linuxfromscratch.org/BLFS/other/certdata.txt"
"root.crt" = "http://www.cacert.org/certs/root.crt"