[metadata]
name = "ca-certificates"
description = "PKI verifies unknown identities over untrusted networks using a chain of trust and Mozilla provides trusted certificates for LFS-8.1."
version = "1.0.0"
provides = ["/usr/sbin/make-ca.sh"]
deps = []

[downloads]
"root.crt" = "http://www.cacert.org/certs/root.crt"