[metadata]
name = "xinit"
version = "1.4.2"
description = "The xinit package contains a usable script to start the xserver."
deps = []
provides = ["/usr/bin/xinit", "/usr/bin/startx"]

[downloads]
"xinit-1.4.2.tar.xz" = "https://www.x.org/pub/individual/app/xinit-1.4.2.tar.xz"