[metadata]
name = "xorg-video-intel"
version = "20230223"
description = "The Xorg Intel Driver package contains the X.Org Video Driver for Intel integrated video chips including 8xx, 9xx, Gxx, Qxx, HD, Iris, and Iris Pro graphics processors."
deps = []
provides = [
  "/usr/bin/intel-virtual-output",
  "/usr/lib/libIntelXvMC.so",
  "/usr/lib/xorg/modules/drivers/intel_drv.so"
]

[downloads]
"xf86-video-intel-20230223.tar.xz" = "https://anduin.linuxfromscratch.org/BLFS/xf86-video-intel/xf86-video-intel-20230223.tar.xz"