[metadata]
name = "vim"
version = "9.0.1503"
description = "The Vim package, which is an abbreviation for VI IMproved, contains a vi clone with extra features as compared to the original vi."
deps = ["utils/rsync"]
provides = [
  "/usr/bin/ex",
  "/usr/bin/rview",
  "/usr/bin/rvim",
  "/usr/bin/vi",
  "/usr/bin/vim",
  "/usr/bin/view",
  "/usr/bin/vimdiff",
  "/usr/bin/vimtutor",
  "/usr/bin/xxd"
]

[downloads]
"vim-9.0.1503.tar.gz" = "https://anduin.linuxfromscratch.org/BLFS/vim/vim-9.0.1503.tar.gz"