[metadata]
name = "fribidi"
version = "1.0.13"
description = "The FriBidi package is an implementation of the Unicode Bidirectional Algorithm (BIDI). This is useful for supporting Arabic and Hebrew alphabets in other packages."
deps = []
provides = ["/usr/bin/fribidi", "/usr/lib/libfribidi.so"]

[downloads]
"fribidi-1.0.13.tar.xz" = "https://github.com/fribidi/fribidi/releases/download/v1.0.13/fribidi-1.0.13.tar.xz"