[metadata]
name = "nano"
version = "7.2"
description = "The Nano package contains a small, simple text editor which aims to replace Pico, the default editor in the Pine package."
deps = []
provides = ["/usr/bin/nano"]

[downloads]
"nano-7.2.tar.xz" = "https://www.nano-editor.org/dist/v7/nano-7.2.tar.xz"