[metadata]
name = "firefox"
version = "114-0.1"
description = "This package installs the prebuilt binaries for the firefox browser"
deps = ["net/wget", "system/pulseaudio", "graphics/gtk3", "libs/dbus-glib"]
provides = [
  "/usr/bin/firefox",
  "/usr/share/applications/firefox.desktop"
]

[downloads]
"firefox-114.0.1.tar.bz2" = "https://download-installer.cdn.mozilla.net/pub/firefox/releases/114.0.1/linux-x86_64/es-ES/firefox-114.0.1.tar.bz2"
