[metadata]
name = "dash"
description = "Dash is a lightweight POSIX-compliant shell used as an alternative to Bash with fast startup and low memory usage."
version = "0.5.12"
provides = ["/bin/dash"]
deps = []

[downloads]
"dash-0.5.12.tar.gz" = "http://gondor.apana.org.au/~herbert/dash/files/dash-0.5.12.tar.gz"