[metadata]
name = "xorg"
version = "unspecified (pkgs-collection)"
description = "This package contains the base packages for the Xorg implementation to work"
provides = []
deps = [
  "graphics/fontconfig",
  "net/wget",
  "net/curl",
  "libs/mako",
  "dev/llvm",
  "display-servers/wayland-protocols",
  "libs/pixman",
  "libs/libepoxy",
  "libs/libtirpc",
]

[downloads]