[metadata]
name = "nasm"
version = "2.16.01"
description = "NASM (Netwide Assembler) is an 80x86 assembler designed for portability and modularity. It includes a disassembler as well."
deps = []
provides = ["/usr/bin/nasm", "/usr/bin/ndisasm"]

[downloads]
"nasm-2.16.01.tar.xz" = "https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.xz"