[metadata]
name = "p11-kit"
version = "0.24.1"
description = "The p11-kit package provides a way to load and enumerate PKCS #11 (a Cryptographic Token Interface Standard) modules."
deps = ["libs/libtasn1"]
provides = [
  "/usr/bin/p11-kit",
  "/usr/bin/trust",
  "/usr/bin/update-ca-certificates",
  "/usr/lib/libp11-kit.so",
  "/usr/lib/p11-kit-proxy.so"
]

[downloads]
"p11-kit-0.24.1.tar.xz" = "https://github.com/p11-glue/p11-kit/releases/download/0.24.1/p11-kit-0.24.1.tar.xz"