[metadata]
name = "bash"
version = "5.2.15"
description = "bash stands for bourne again shell"
deps = []
provides = ["/usr/bin/bash", "/bin/bash"]

[downloads]
"bash-5.2.15.tar.gz" = "https://mirror.cedia.org.ec/gnu/bash/bash-5.2.15.tar.gz"